apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base/installs/multi-user
  - ../../base/metadata/base
  - ../../base/metadata/options/istio
  - ../../third-party/argo/installs/cluster
  - ../../third-party/minio/base
  - ../../third-party/minio/options/istio
  - ../../third-party/metacontroller/base

commonLabels:
  application-crd-id: kubeflow-pipelines

configMapGenerator:
- name: pipeline-install-config
  env: params.env
  behavior: merge
secretGenerator:
- name: mysql-secret
  env: secret.env
  behavior: merge

namespace: kubeflow
