apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
spec:
  storageClassName: efs-sc
  volumeName: efs-control-plane-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
